---
Description: 'Salmoncow'
# aws cloudformation create-stack --stack-name salmoncow --template-body file://main.yaml
# aws cloudformation create-change-set --stack-name salmoncow --change-set-name salmoncow2 --use-previous-template
# aws cloudformation update-stack --stack-name salmoncow --template-body file://main.yaml
# aws cloudformation delete-stack --stack-name salmoncow

Mappings: 
  StackTags:
    Tags:
      tags:
        - Key: deployment
          Value: cloudformation
        - Key: owner
          Value: salmoncow
        - Key: use_case
          Value: td000

Resources:
    Route53ZoneCFSalmoncowCom:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: https://salmoncow.s3.amazonaws.com/cloudformation_stacks/route53_zone.yaml
        Tags: !FindInMap [StackTags, Tags, tags]
        Parameters:
          Name: moo.salmoncow.com
          Comment: test

Outputs:
  Route53ZoneCFSalmoncowComStackId:
    Value: !Ref Route53ZoneCFSalmoncowCom
  Route53ZoneCFSalmoncowComZoneId:
    Value: !GetAtt Route53ZoneCFSalmoncowCom.Outputs.ZoneId
  Route53ZoneCFSalmoncowComNameServers:
    Value: !GetAtt Route53ZoneCFSalmoncowCom.Outputs.NameServers
          